service: serverless-reminders

provider:
  name: aws
  runtime: nodejs8.10
  iamRoleStatements:
    -  Effect: "Allow"
       Action:
         - "ses:*"
       Resource:
         - "*"

functions:
  dailyReminder:
    handler: handler.sendReminderDaily
    events:
      - schedule: rate(1 day)
  weekendReminder:
    handler: handler.sendReminderWeekend
    events:
      - schedule: cron(30 22 ? * SUN,SAT *)

